- .env.example
- Dockerfile
- modules/Layout/Branding/Branding.tsx
- modules/Layout/Branding/utils.ts
- package-lock.json
- package.json
+ Add fallbacks if theme preset is not loaded
> [TITS-5139] Load Bea theme preset instead of active theme

- hooks/useInfiniteLoading.ts
- modules/Galleries/lib/useInfiniteGalleriesLoading.ts
- modules/InfiniteStories/lib/useInfiniteStoriesLoading.ts
Since we won't go with extracting the hook at least we can bring the small refactoring. First seen here: https://github.com/prezly/theme-kit-nextjs/pull/18
> Slightly refactored useInfiniteLoading hook

- modules/Layout/Header/SearchWidget/components/MainPanel.tsx
Demo: 
https://user-images.githubusercontent.com/43710420/161784215-3dbc570a-eb00-4892-99f8-9cc3a0a0ed49.mov
> [TF-584] Search modal without categories, still shows categories title

- components/RichText/styles.module.scss
- modules/Layout/Branding/Branding.tsx
- styles/variables/_typography.scss
> [MT-4873] Added support for bold headings

- modules/Layout/Footer/DataRequestLink.tsx
- modules/Layout/Footer/Footer.tsx
@oleg-semyonov Can you please port this over to other themes? 🙏
> [HD-60] Custom Data Request link

- components/RichText/Quote.module.scss
- components/RichText/Quote.tsx
How it looks on the various alignments
> [DEV-5526] Update quotes UI

- modules/Category/Category.tsx
- modules/Galleries/Galleries.tsx
- modules/InfiniteStories/InfiniteStories.tsx
- modules/Stories/Stories.tsx
- package-lock.json
- package.json
- pages/[slug].tsx
- pages/category/[slug].tsx
- pages/index.tsx
- pages/media/album/[uuid].tsx
- pages/media/index.tsx
- pages/s/[uuid].tsx
- types.ts
This PR is complementing the changes made in https://github.com/prezly/theme-kit-nextjs/pull/31
> [TF-750] Move page props fetching logic into the Theme Kit

- modules/Layout/Boilerplate/Boilerplate.tsx
- modules/Layout/Boilerplate/utils.ts
- modules/Layout/Footer/DataRequestLink.tsx
- modules/Story/Embargo/Embargo.tsx
- modules/Story/Story.tsx
- modules/Story/lib/index.ts
- modules/Story/lib/isEmbargoStory.ts
- modules/Story/types/EmbargoStory.ts
- modules/Story/types/index.ts
- package-lock.json
- package.json
- utils/capitaliseFirstLetter.ts
- utils/index.ts
This PR complements the changes made in https://github.com/prezly/theme-kit-nextjs/pull/32
> [TF-799] move generic utility functions to theme kit

- components/RichText/styles.module.scss
this targets blockquotes inside htmlContent
> [TF-953] Bea Bug: Weird text formatting on Story

- package-lock.json
- package.json
- pages/_document.tsx
- sentry.client.config.js
- sentry.server.config.js
- tsconfig.json
Together with reducing boilerplate even more, this update brings fixes to the linked Linear issues.
> [TF-889 TF-1007] Use shared document and sentry config from Theme Kit

- components/RichText/List.tsx
- components/RichText/Quote.module.scss
- components/RichText/Quote.tsx
- components/RichText/styles.module.scss
Same as what I did for the Marcel theme on https://github.com/prezly/theme-nextjs-marcel/pull/143
Applied the same fixes for Bea
> [TF-1041] Fix `Quote` and `List` alignments

- package-lock.json
- package.json
> [MT-5208] Bump @prezly/content-renderer-react-js

- components/ContactCard/ContactCard.module.scss
- components/ContactCard/ContactCard.tsx
1) removed the website link since it was not in the figma design.
2) facebook icon is different from the one on figma, in figma the icon is a square shape and in the code it had 50% border radius: (i checked in the prezly icons, a square one is not available)
> [TF-949] Feature/tf 949 bea greta improvements new contacts

- components/ContactCard/ContactCard.module.scss
> [QRF-134] Remove padding around contact card

- components/PageTitle/PageTitle.module.scss
- components/SlateRenderer/SlateRenderer.module.scss
- modules/Galleries/Galleries.module.scss
- modules/Galleries/GalleriesList.module.scss
- modules/Galleries/GalleriesList.tsx
- modules/InfiniteStories/InfiniteStories.module.scss
- modules/InfiniteStories/InfiniteStories.tsx
- modules/Layout/Layout.module.scss
- modules/Search/SearchPage.module.scss
- modules/Search/SearchPage.tsx
- modules/Search/components/Results.module.scss
- modules/Search/components/Results.tsx
- modules/Story/Story.module.scss
- Moved all vertical spacing around the content from child blocks into the `Layout` component for consistency
- Cleaned up styles
- Add styles to remove bottom margin on the last block in the story.
> [CARE-1075] Unify vertical spacing of content

- modules/Search/components/Facet.module.scss
| Before | After |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/67554982/232416312-c91b1493-a810-44b2-af7c-d5935ccaac8b.png) | ![image](https://user-images.githubusercontent.com/67554982/232415924-050e3480-6257-4a6e-b5e4-87e20419e394.png) |
| ![image](https://user-images.githubusercontent.com/67554982/232416445-0c59fffc-7788-4fce-a45f-c04af7e11e25.png) | ![image](https://user-images.githubusercontent.com/67554982/232416008-cae29677-7acc-41e2-9a28-ae1b52607bdb.png) |
| ![image](https://user-images.githubusercontent.com/67554982/232416669-36167186-c4f0-4c66-9217-a205c166d22e.png) | ![image](https://user-images.githubusercontent.com/67554982/232416051-adfcfdda-eb97-4cc5-b9e7-f26addb789a8.png) |
> [CARE-1414] Ensure there is enoguh space for filters dropdown items

- components/StoryLinks/StoryLinks.module.scss
- modules/Story/Story.module.scss
- modules/Story/Story.tsx
- utils/getHeaderAlignment.ts
- utils/index.ts
> [CARE-2137] Date and social icons alignment in themes

- modules/Layout/Boilerplate/Boilerplate.module.scss
> [CARE-3129] Preserve line breaks in address

- app/layout.tsx
- modules/Layout/Routing.tsx
- theme-kit/router/createRouter.ts
- theme-kit/router/route.ts
- theme-kit/routing.ts
- theme-kit/useRouting.tsx
based on the theme router configuration with type safety
> [DEV-11929] Feature - Client-side URL generation

- app/[localeCode]/(story)/[slug]/page.tsx
- app/layout.tsx
- components/StoryImage/FallbackProvider.tsx
- components/StoryImage/StoryImage.tsx
- components/StoryImage/index.ts
Most of the conversion has been done in scope of #958 
The only problem was the missing context for the StoryImage fallback content
> [DEV-11945] Fix - Search widget

- adapters/client/intl.ts
- adapters/client/routing.ts
- adapters/client/theme-settings.ts
- adapters/server/locale.ts
- middleware.ts
- modules/Intl/IntlProvider.tsx
- package-lock.json
- package.json
- https://github.com/prezly/theme-kit-js/pull/485
- https://github.com/prezly/theme-kit-js/pull/486
> [DEV-12062] Refactor - Move code around

- adapters/server/metadata.ts
- adapters/server/routing.ts
- app/[localeSlug]/(index)/page.tsx
- app/[localeSlug]/layout.tsx
- app/[localeSlug]/loading.tsx
- components/NotificationsBar/LinkedText.tsx
- components/RichText/Html.tsx
- components/StoryCards/HighlightedStoryCard.tsx
- components/StoryCards/StoryCard.tsx
- components/StoryImage/StoryImage.module.scss
- middleware.ts
- modules/CookieConsent/components/CookieConsentBar.module.scss
- modules/SubscribeForm/ui/SubscribeForm.tsx
- package-lock.json
- package.json
- styles/variables/_shadows.scss
> [CARE-3731] Fix - Improve client side performance lighthouse score

- middleware.ts
Optimize middleware to optionally get newsroom locales from HTTP header
> [DEV-12039] Optimize - Middleware to get newsroom locales from header

- .github/workflows/build-and-push.yml
This reverts commit 8b5e3bc917657cf75e72d01257cf2831604a8fb9.
> [DEV-12314] Promote Bea Next to mainline 

- components/ContentRenderer/components/Attachment/DownloadLink.tsx
- components/StoryLinks/StoryShareUrl.tsx
- modules/Contacts/ui/Contacts.tsx
- modules/CookieConsent/components/CookieConsentBar.tsx
- modules/Header/Categories.tsx
- modules/Header/Header.tsx
- modules/Header/ui/CategoriesNav/CategoriesNav.tsx
- modules/Header/ui/Header.tsx
- modules/Header/ui/SearchWidget/components/CategoriesList.tsx
- modules/Header/ui/SearchWidget/components/SearchBar.tsx
- modules/Header/ui/SearchWidget/components/SearchResults.tsx
- modules/InfiniteStories/InfiniteStories.tsx
- modules/InfiniteStories/StoriesList.tsx
- modules/Search/components/Facet.tsx
- modules/Search/components/SearchBar.tsx
- modules/Search/components/Subtitle.tsx
- modules/SubscribeForm/ui/SubscribeForm.tsx
- package-lock.json
- package.json
See https://github.com/prezly/theme-kit-js/pull/601 for details.
> [DEV-12530] Feature - Enrich media gallery page title and description

- components/ContentRenderer/ContentRenderer.module.scss
- package-lock.json
- package.json
> [UI-566] Feature - Re-enable captions in galleries on hover

- modules/Stories/Stories.tsx
If there's only one story in the entire site, it doesn't make sense to display the filters in this case.
> Fix - Do not display category filters if there's only one story

- app/[localeCode]/category/[slug]/page.tsx
- components/PageTitle/PageTitle.module.scss
- modules/Category/Category.module.scss
- modules/Category/Category.tsx
> [DEV-12682] Feature - Display category image on category page

- app/[localeCode]/layout.tsx
- app/[localeCode]/media/album/[uuid]/page.tsx
- modules/Analytics/AnalyticsProvider.tsx
- modules/Broadcast/BroadcastGallery.tsx
- modules/Broadcast/index.ts
- package-lock.json
- package.json
Uses the same approach as in https://github.com/prezly/theme-nextjs-bea/pull/1126. Requires changes from https://github.com/prezly/analytics/pull/300.
> [DEV-12777] Feature - Pass media gallery UUID into analytics provider to allow better tracking

- modules/Analytics/AnalyticsProvider.tsx
> [CARE-4994] Feature - Use the rollup domain for Plausible

- package-lock.json
- package.json
Updated the theme kit to include changes from https://github.com/prezly/theme-kit-js/pull/682.
> [CARE-4999] Feature - Update CSP header to allow iframing

- package-lock.json
- package.json
See https://github.com/prezly/content-renderer-react-js/pull/83
> [CARE-5169] Bump @prezly/content-renderer-react-js

- modules/SubscribeForm/ui/SubscribeForm.tsx
> [DEV-12305] Feature - Allow browser to suggest email address completion

- package-lock.json
- package.json
Related changes: https://github.com/prezly/content-renderer-react-js/pull/86
> [CARE-5260] Bump `@prezly/content-renderer-react-js`

- app/[localeCode]/(index)/page.tsx
- app/[localeCode]/category/[slug]/page.tsx
- components/StaggeredLayout/StaggeredLayout.module.scss
- components/StaggeredLayout/StaggeredLayout.tsx
- components/StaggeredLayout/index.tsx
- modules/Category/Category.tsx
- modules/InfiniteStories/InfiniteStories.tsx
- modules/InfiniteStories/StoriesList.tsx
- modules/Stories/Stories.tsx
- theme-settings.ts
- utils/getStoryListPageSize.ts
- utils/index.ts
- utils/parsePreviewSearchParams.ts
> [CARE-5671] Feature - Add support for masonry layout

- package-lock.json
- package.json
See https://github.com/prezly/theme-kit-js/releases/tag/v9.6.1
> [CARE-5740] Fix gallery page meta description

- adapters/server/app.ts
- components/ContentRenderer/ContentRenderer.tsx
- package-lock.json
- package.json
> [DEV-13192] Add support for coverage cards

- modules/Head/components/BrandingSettings.tsx
- modules/Head/components/getCssVariables.ts
- styles/_typography.scss
- theme-settings.ts
- added support for more fonts
- some fonts now have a secondary font
- in this case, primary font is used only for headings
> [DEV-13354] Add support for more fonts

- components/StoryCards/HighlightedStoryCard.module.scss
- components/StoryCards/HighlightedStoryCard.tsx
- fixed image overflowing the card when hovered
- added underline effect when hovering the card
- fixed placeholder being displayed incorrectly
> Fixes for full width featured story

- components/RichText/Quote.module.scss
- components/RichText/styles.module.scss
> [CARE-6380] Feature/spacing improvements

- adapters/server/routing.ts
- app/[localeCode]/tag/[tag]/page.tsx
- app/api/stories/route.ts
- modules/InfiniteStories/InfiniteStories.tsx
- modules/Tag/Tag.module.scss
- modules/Tag/Tag.tsx
- modules/Tag/index.ts
- next-env.d.ts
- package-lock.json
- package.json
> [CARE-6533] Add Tag page to Bea

- package-lock.json
- package.json
Reverts prezly/theme-nextjs-bea#1221
> Revert "Update @prezly/sdk to v23.7.2"

- app/[localeCode]/(story)/[slug]/page.tsx
- app/[localeCode]/(story)/preview/[uuid]/page.tsx
- app/[localeCode]/(story)/secret/[uuid]/page.tsx
- modules/Story/RelatedStories/RelatedStories.tsx
- modules/Story/RelatedStories/index.ts
- modules/Story/Story.tsx
> [DEV-19367][PRD-1243] Feature - Story - Latest stories section

- components/ContentRenderer/components/Attachment/Attachment.module.scss
- components/ContentRenderer/components/Attachment/Attachment.tsx
- components/ContentRenderer/components/Attachment/utils.ts
See https://linear.app/prezly/issue/DEV-18744/attachment-embeds-look-bad-in-campaigns#comment-e25c5a7c
> [DEV-18744] Feature - Update attachment presentation

- components/ContentRenderer/ContentRenderer.module.scss
> [DEV-19717] Fix - buttons responsiveness

- components/FormInput/FormInput.tsx
- modules/Header/ui/SearchWidget/components/SearchBar.tsx
Setting `autoFocs={true}` on the input does not work
> [DEV-20025] Fix - Set focus on input when search widget is opened

- package.json
- pnpm-lock.yaml
https://github.com/prezly/content-renderer-react-js/releases/tag/v0.41.1
> [DEV-20150] Bump the content renderer version

- src/components/RichText/styles.module.scss
> [DEV-20186] Force table border

- app/[localeCode]/(story)/[slug]/page.tsx
- app/[localeCode]/(story)/preview/[uuid]/page.tsx
- app/[localeCode]/(story)/secret/[uuid]/page.tsx
- src/modules/Story/Story.tsx
> [PRD-1349] Fix - Use badges for categories when boxed story card variant is selected

- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
- src/modules/InfiniteHubStories/InfiniteHubStories.tsx
> [DEV-20509] Fix - Add "Latest stories" title between sites and stories in hub sites

- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
- src/modules/InfiniteHubStories/InfiniteHubStories.tsx
- src/modules/Search/components/SearchBar.tsx
- src/modules/Search/components/Subtitle.tsx
- improved search page
- hide number of results if it's zero
- hide filters if there's no facets to filter with
- added "Go to site X" title to site logos
- added scale effect to site logos on hover
> [DEV-20511][DEV-20510][DEV-20508] Fix - Various tweaks for hub rooms and search

- src/modules/Search/components/SearchBar.module.scss
- src/modules/Search/components/SearchBar.tsx
Not sure what was the reasoning behind having it but it's been there since 2022, so long forgotten history now.
> [DEV-20591] Fix - Get rid of custom wrapper around search bar

- package.json
- pnpm-lock.yaml
- src/components/ContactCard/ContactCard.tsx
- src/components/GalleryCard/GalleryCard.tsx
- src/components/SocialShare/SocialShare.tsx
- src/modules/Header/ui/Header.module.scss
- src/modules/Header/ui/Header.tsx
- src/modules/Header/ui/Logo/Logo.tsx
First round of accessibility fixes to get us closer to the WCAG compliance.
- removed duplicate `alt` attribute in story images, story galleries and regular media galleries
- added `aria-label` attribute to the sharing icons
> [DEV-20684] Fix - Addressing accessibility issues

- package.json
- pnpm-lock.yaml
- src/components/ContactCard/ContactCard.tsx
- src/modules/Boilerplate/ui/Boilerplate.tsx
- src/modules/SubscribeForm/ui/SubscribeForm.tsx
I went over all pages with the [Axe](https://www.npmjs.com/package/@axe-core/cli) library and fixed all of the reported issues.
We can get this deployed and then run the tests on the production sites and see if there are any more problems.
> [DEV-20684] Fix - Another set of accessibility fixes

- package.json
- pnpm-lock.yaml
- src/modules/Story/Share/Share.tsx
Uses new strings from https://github.com/prezly/theme-kit-js/releases/tag/v10.4.0
> [DEV-21506] Fix - Untranslated strings

- package.json
- pnpm-lock.yaml
See the changes here https://github.com/prezly/content-renderer-react-js/pull/105
> [DEV-21347] Feature - Support expanded tables properly

- package.json
- pnpm-lock.yaml
I've released a new version of the content renderer but forgot to push my changes before merging 🙈
> Fix - Update content renderer

- src/modules/Header/Header.tsx
- src/modules/Header/ui/Header.tsx
- src/theme-settings.ts
With no label defined:
With label defined:
> [DEV-21610] Feature - Use main_site_label if it's defined

- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
I forgot to center the columns when there's only two.
> Fix - Add missing justify

- src/components/StoryCards/HighlightedStoryCard.module.scss
Forgot to update the code also in the HighlightedStoryCard
> Remove the underline also in the highlighted story card

- Dockerfile
- Dockerfile.preview
See https://prezly.slack.com/archives/C029N538J/p1759733117568819?thread_ts=1759521128.253869&cid=C029N538J
> Revert uploadcare CDN - Host missing from `content-security-policy` headers
