- components/ContactCard/ContactCard.tsx
- components/SlateRenderer/components/Attachment/Attachment.tsx
- modules/analytics/components/Analytics.tsx
- Added `id` attributes to the content-renderer nodes overridden by Bea
- Added auto-clicking assets when navigation from email campaigns
> [TITS-5142] Add support for email media

- package-lock.json
- package.json
See https://github.com/prezly/content-renderer-react-js/releases/tag/v0.12.0
* [MT-4675] Fix - Preserve soft breaks by @e1himself in https://github.com/prezly/content-renderer-react-js/pull/11
* [DEV-5016] Fix - Gallery server-side rendering by @e1himself in https://github.com/prezly/content-renderer-react-js/pull/12
* [DEV-5028] Fix - Gallery image download in original size by @e1himself in https://github.com/prezly/content-renderer-react-js/pull/13
* Fix  - Images popover accessibility (and SSR) improvements by @e1himself in https://github.com/prezly/content-renderer-react-js/pull/14
> [MT-4675][DEV-5016] Upgrade @prezly/content-renderer-react-js to v0.12

- package-lock.json
- package.json
- `de_BE` and `es-419`, see https://github.com/prezly/theme-kit-nextjs/pull/14
> [DEV-5120][DEV-5082] Added support for new cultures

- modules/Layout/CookieConsentBar/CookieConsentBar.module.scss
- modules/Layout/CookieConsentBar/CookieConsentBar.tsx
This is something that we forgot to implement but luckily the feature itself is not used by a lot of licenses yet.
When defined in the main app, the returned string contains HTML paragraph(s), so we just need to wrap them in a div.
The editor also supports strong, italic, underline and links.
> [HD-81] Support custom cookie statement

- hooks/index.ts
- hooks/useDisplayedLanguages.ts
- modules/Layout/Header/Header.tsx
- modules/Layout/Header/LanguagesDropdown/LanguagesDropdown.tsx
As mentioned in the ticket, when a user doesn't use categories or languages we should hide the mobile menu toggler.
One more case to notice is when the user has a gallery but no images in it, so I tried to handle that case as well.
> [TF-939] Bea/Greta Bug: Remove hamburguer icon when there is no content in menu

- components/StoryCards/StoryCard.module.scss
- components/StoryCards/StoryCard.tsx
- styles/mixins/_images.scss
> [TF-945] Bea improvements: Smaller Story Cards

- components/RichText/styles.module.scss
How it looks now, aligned with how quotes in general looks
> [TF-1038] Unusual vertical line & space appearing before Quoted Text block

- theme-kit/router/UrlGenerator.ts
- theme-kit/router/createRouter.ts
- theme-kit/router/index.ts
- theme-kit/routing.ts
- Implement a wrapper around `Router.generate()` to support `localeSlug` or `localeCode` interchangeably.
> [DEV-11815] Feature - Typed URL generator

- adapters/server/api.ts
Attach `x-newsroom-uuid` header to all API requests
See https://github.com/prezly/ops/pull/108
> [DEV-12019] Next.js 13 - API cache layer

- .github/workflows/build-and-push.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- modules/Gallery/Gallery.module.scss
Contained keeps the current width of 720px and expanded becomes 1120px, which is the width of the newsroom's container (minus paddings).
I've also changed the margins of the page itself, so the title is the same position as other pages (albeit offseted).
> [DEV-12518] Feature - Make "expanded" media gallery 1120px wide

- modules/Gallery/Gallery.module.scss
- modules/Gallery/Gallery.tsx
- package-lock.json
- package.json
- metadata was fixed in https://github.com/prezly/theme-kit-js/pull/591
- also increased the width of the gallery page, with `contained` gallery keeping the current 720px width and `expanded` will become 100% container width (1120px)
- replaced the title and description with the `PageTitle` component so it's more consistent with other pages
- also fixed spacing issues on the social links
> [DEV-12530] Fix - Use gallery's description for metadata

- modules/Header/ui/CategoriesNav/CategoriesNavDesktop.module.scss
- modules/Header/ui/Header.module.scss
- modules/Search/components/SearchBar.module.scss
- styles/mixins/_container.scss
- styles/mixins/_responsive.scss
- styles/variables/_breakpoints.scss
- styles/variables/_spacing.scss
Preview: https://theme-nextjs-bea-preview-crlieg74x-prezly1.vercel.app/
- removed mobile breakpoint so now the mobile header appears below tablet breakpoint (767px)
- reduced max-width of logo on mobile
- increased max-width of categories dropdown content on desktop
- regular categories in categories dropdown will now have the hover state when focused as well
> [DEV-12670] Increase mobile breakpoint and remove large desktop breakpoint

- components/Dropdown/DropdownItem.module.scss
- modules/Header/ui/CategoriesNav/CategoriesNavDesktop.module.scss
- modules/Header/ui/CategoriesNav/CategoriesNavMobile.module.scss
- modules/Header/ui/CategoriesNav/CategoriesNavMobile.tsx
- modules/Header/ui/CategoriesNav/CategoryItem.module.scss
- modules/Header/ui/CategoriesNav/CategoryItem.tsx
- modules/Header/ui/CategoriesNav/FeaturedCategory.module.scss
- modules/Header/ui/CategoriesNav/FeaturedCategory.tsx
- modules/Header/ui/Header.module.scss
- modules/Header/ui/LanguagesDropdown/LanguagesDropdown.module.scss
- modules/Header/ui/LanguagesDropdown/LanguagesDropdown.tsx
Preview: https://theme-nextjs-bea-preview-gafk9kw9t-prezly1.vercel.app/
- mobile menu and categories dropdown hardcoded to use the text color
- added faint gray background to opened dropdowns in mobile menu
- fixed layout of featured categories in categories dropdown on desktop
> [DEV-12675] FIx - Improved mobile menu styling, desktop categories menu layouts and hardcoded colors

- package-lock.json
- package.json
Actual fix is in https://github.com/prezly/analytics/pull/302.
> [DEV-12794] Fix - Do not track links with Uploadcare CDN as outbound

- app/[localeCode]/layout.tsx
- components/PreviewPageMask/PreviewPageMask.module.scss
- components/PreviewPageMask/PreviewPageMask.tsx
- components/PreviewPageMask/index.ts
Implemented a component that creates a fixed overlay covering the entire page, preventing the user from clicking anything, but still allow scrolling.
This functionality only works when `preview=true` query parameter is present and is intended to work with our live theme preview functionality.
> [CARE-5022] Feature - Create a mask when preview=true query parameter is present

- hooks/useThemeSettingsWithPreview/useThemeSettingsWithPreview.ts
- modules/Head/components/DynamicPreviewBranding.tsx
- utils/index.ts
- utils/parsePreviewSearchParams.ts
So, the problem here was that I was re-using the `useThemeSettingsWithPreview` hook which uses `useThemeSettings` which relies on context from `ThemeSettings`, but because `DynamicPreviewBranding` is rendered outside of `ThemeSettingsProvider`, it was injecting the default theme settings instead of the newsroom one's.
> [CARE-5028] Fix - Parse preview search params in DynamicPreviewBranding

- components/PreviewPageMask/PreviewPageMask.tsx
- hooks/index.ts
- hooks/useMaskParam.ts
- modules/CookieConsent/components/CookieConsentBar.tsx
When live previewing the theme, we use the `mask` parameter to prevent clicking inside the page, but cookie consent bar could still appear.
With this change, the cookie bar will not be rendered.
> [CARE-5202] Feature - Hide cookie bar if mask parameter is present

- app/[localeCode]/layout.tsx
- components/WindowScrollListener/WindowScrollListener.tsx
- components/WindowScrollListener/index.ts
We need to be able to preserve the scroll position when live previewing the theme, but since it's not possible to access the scroll position of the iframe, we need this extra code to provide the scroll position when scrolling happens.
Similarly, we also need to listen to the messages from the parent so we can restore the scroll position after the iframe is reloaded.
> [CARE-5201] Feature - Allow communication between the theme and the parent

- app/[localeCode]/category/[slug]/page.tsx
I think it doesn't make sense to show the category page if there's no stories published in it.
> [DEV-12308] Feature - Show a 404 page if category is empty

- package-lock.json
- package.json
I'll make sure to merge it once https://github.com/prezly/prezly/pull/14931 is merged. I'll update the rest of themes to new content renderer version, as I have to do it anyway :) So doing it as part of CARE-5260
> [CARE-5260][DEV-13053] Bump `@prezly/content-renderer-react-js` to `0.38.3`

- components/StaggeredLayout/StaggeredLayout.tsx
- components/StoryCards/StoryCard.module.scss
- components/StoryCards/StoryCard.tsx
- components/StoryImage/StoryImage.module.scss
- components/StoryImage/StoryImage.tsx
- modules/InfiniteStories/StoriesList.module.scss
- modules/InfiniteStories/StoriesList.tsx
A follow-up to #1164 since I've noticed the cards are not displayed the same way as in Greta theme, which we're trying to emulate.
> [CARE-5671] Fix - Tweak staggered layout to show images properly

- components/StoryCards/StoryCard.module.scss
With the masonry layout, I've noticed that cards have a weird empty space below the image which makes the border stand out.
Resetting font size to 0 in the container makes it look correct.
> Fix - Set font size to 0 to prevent border overflow

- components/StoryImage/StoryImage.module.scss
- components/StoryImage/StoryImage.tsx
Added fixed aspect ratio on stories without image, so the masonry layout is more obvious, otherwise if there's a lot of stories without a cover image, it looks very similar to the regular grid layout.
Before
After
> Fix - Use 1.5 aspect ratio for placeholders in staggered layout

- adapters/server/search.ts
Those are same fallback values as we use in theme-kit: https://github.com/prezly/theme-kit-js/blob/7.x/packages/core/src/data-fetching/lib/getSearchSettings.ts#L13-L18
> [DEV-13150] Feature - Add Meilisearch & Algolia ENV variables fallbacks

- app/[localeCode]/(index)/page.tsx
- components/CategoriesBar/CategoriesBar.tsx
- components/CategoriesBar/CategoryItem/CategoryItem.tsx
- components/StoryCards/HighlightedStoryCard.module.scss
- components/StoryCards/HighlightedStoryCard.tsx
- components/StoryCards/StoryCard.tsx
- components/StoryImage/StoryImage.tsx
- components/StoryImage/lib.ts
- modules/InfiniteStories/InfiniteStories.tsx
- modules/InfiniteStories/StoriesList.tsx
- modules/Stories/Stories.tsx
- theme-settings.ts
- utils/parsePreviewSearchParams.ts
The entire card is clickable minus the category badges, with a hover state similar to the other story cards.
Desktop:
Tablet:
Mobile:
> [DEV-13393] Implement Lena-style hero card

- components/StoryCards/HighlightedStoryCard.module.scss
- components/StoryCards/HighlightedStoryCard.tsx
- also noticed the vertical paddings on mobile and tablet were using desktop numbers, so I've tweaked that
> [DEV-13405] Display story date in full width featured story

- modules/Boilerplate/ui/Boilerplate.module.scss
- modules/Footer/ui/Footer.module.scss
> [CARE-6113] Feature - Change Bea footer links to use an underline

- components/StoryCards/StoryCard.tsx
- components/StoryImage/StoryImage.tsx
- modules/InfiniteStories/StoriesList.tsx
- package-lock.json
- package.json
See https://linear.app/prezly/issue/CARE-5657/innogames-blurry-cover-images-in-home-site-for-stories-published#comment-92259c27
https://github.com/user-attachments/assets/0f5793f7-268f-4e53-94e6-c38c80e15230
https://github.com/user-attachments/assets/51ac7dad-9ccb-4e98-ad41-b62afbcacdd4
> [CARE-5657] Fix - Crop to aspect ratio before passing to the renderer

- components/ContentRenderer/components/Attachment/Attachment.tsx
- package.json
- pnpm-lock.yaml
The type is re-exported by `@prezly/sdk`
> [DEV-18744] Fix usage of a non-direct dependency

- components/Modal/Modal.tsx
- modules/Header/ui/SearchWidget/components/SearchHit.tsx
- modules/Header/ui/SearchWidget/components/SearchResults.tsx
- clicking the backdrop now closes the search
- fixed `onClick` handler on `SearchHit` component
> [DEV-19797] Fix - Search widget fixes

- components/ContentRenderer/components/Attachment/Attachment.module.scss
> [DEV-19988] Fix - attachment card with long name breaking responsive design

- src/components/RichText/styles.module.scss
Before the change, the styles were relying on browser defaults. 
- Which was inconsistent
- Did not take into account background color, and could made the borders practically invisible for certain configurations
- Lacked in-cells and bottom spacing
BEFORE: 
AFTER:
> [DEV-20186] Fix styles of in-raw-HTML tables

- src/modules/Header/ui/Header.tsx
Use non-h1 tag for the site logo
Otherwise all pages have 2 h1 tags on them.
See https://linear.app/prezly/issue/OPS-590/rac-seo-questions-after-migration#heading-2-multiple-h1s-per-page-see-als-response-below-687410bd
> [DEV-20187] Fix - Multiple h1 tags on pages

- src/modules/Search/components/Facet.tsx
> [DEV-20438] Fix - Sort year filter in descending order

- src/modules/Search/components/SearchBar.tsx
Based on the types it wasn't clear it can be `null`.
> Fix - Do not assume searchResults is always defined

- src/modules/Search/components/Results.module.scss
- src/modules/Search/components/SearchBar.tsx
- src/modules/Search/components/Subtitle.tsx
So turns out the Facet components must be rendered otherwise the attributes won't get sent to Meilisearch and then we can't detect if there's any available facets or not.
Other tweaks include:
- removed subtitle if there's no search query (previously was rendering an empty container)
- removed top padding in empty state on mobile
> Fix - Properly hide filters and other search page tweaks

- app/[localeCode]/category/[slug]/page.tsx
With this change, the languages in the dropdown will point to the homepage if the category does not have any stories in a given language.
> [DEV-20323] Fix - Link to homepage if category does not have stories in a given language

- app/[localeCode]/(index)/page.tsx
Because there is no highlighted story for hubs, we don't need to fetch an extra story.
> [DEV-20594] Fix - Do not fetch extra story on homepage in hub sites

- package.json
- pnpm-lock.yaml
To include this fix: https://github.com/prezly/content-renderer-react-js/pull/99
> [DEV-20679] Bump the content renderer version

- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
- src/modules/InfiniteHubStories/InfiniteHubStories.tsx
- src/modules/InfiniteStories/StoriesList.tsx
- src/modules/InfiniteStories/ui/CategoriesFilters/CategoriesFilters.tsx
Currently, if there's no featured categories in a non-hub site, the "Latest stories" H1 is not rendered at all which is a problem for WCAG (accessibility) guidelines. So the title is now always rendered.
For hub sites, the title was only rendered when there were stories included as well. I've changed this so the title is always rendered and if there's no stories, it's hidden out of the viewport so it's only accessible for the screen readers.
> [DEV-20684] Fix - Always render H1 on homepage

- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
- src/modules/InfiniteHubStories/InfiniteHubStories.tsx
- src/modules/InfiniteStories/StoriesList.tsx
- src/modules/InfiniteStories/ui/CategoriesFilters/CategoriesFilters.module.scss
- src/modules/InfiniteStories/ui/CategoriesFilters/CategoriesFilters.tsx
The "Latest stories" page title is now only rendered as part of `StoriesList` component for both hub and non-hub sites. For hub sites, the title is hidden for regular users but stays visible for screen readers.
> [DEV-20761] Fix - Do not render page title twice for hub sites

- app/[localeCode]/(story)/[slug]/page.tsx
- app/[localeCode]/(story)/preview/[uuid]/page.tsx
- app/[localeCode]/(story)/secret/[uuid]/page.tsx
- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
- src/modules/InfiniteHubStories/InfiniteHubStories.tsx
- src/modules/InfiniteStories/StoriesList.module.scss
- src/modules/InfiniteStories/StoriesList.tsx
- src/modules/InfiniteStories/ui/CategoriesFilters/CategoriesFilters.module.scss
- src/modules/InfiniteStories/ui/CategoriesFilters/CategoriesFilters.tsx
- src/modules/Story/RelatedStories/RelatedStories.tsx
- src/modules/Story/Story.tsx
We need to render the "Latest stories" H1 to be compliant with the WCAG guidelines, however it's not needed visually for most users.
So this is how it works now:
- for non-hub sites
- we only show the title if there's any featured categories
- otherwise we only show it for screen readers
- for hub sites
- we only show the title if there's any included stories
- otherwise we only show it for screen readers
I've also fixed two more things:
1. removed extra bottom margin on the site logos in hub sites if there's no included stories
2. replaced the untranslated "Latest News" string with the translated "Latest stories"
> [DEV-20811] Fix - Hide "Latest stories" H1 on homepage in certain conditions

- app/api/stories/route.ts
- src/modules/Category/Category.tsx
- src/modules/Stories/Stories.tsx
I've changed the `category` parameter to `categories` in one of the newer theme kit versions but Bea wasn't updated since then, so I've missed this error.
Curious that we don't build Bea as part of the PR checks.. we should probably update the Linter check to also run Typescript.
> Fix - Update API calls for stories

- app/[localeCode]/(index)/page.tsx
Hub stories should always use the fixed default stories page size (12) regardless of layout
> [DEV-21638] Used fixed default page size for hub stories

- src/modules/InfiniteHubStories/InfiniteHubStories.module.scss
- src/modules/InfiniteHubStories/InfiniteHubStories.tsx
Switched around the conditions so now the layout is correct when there's 1, 2 or more than 9 logos. For everything in between it works the same.
I've also tweaked the layout for 1 and 2 columns so the logos are smaller and centered.
> [DEV-21762] Fix - Tweak hub site logo layout
